package io.mars.basemanagement.search;

import java.util.Arrays;
import java.util.List;

import javax.inject.Inject;

import io.vertigo.commons.transaction.VTransactionManager;
import io.vertigo.core.lang.Generated;
import io.vertigo.core.lang.ListBuilder;
import io.vertigo.core.node.component.Component;
import io.vertigo.core.node.definition.DefinitionProvider;
import io.vertigo.core.node.definition.DefinitionSpace;
import io.vertigo.core.node.definition.DefinitionSupplier;
import io.vertigo.datafactory.collections.definitions.FacetDefinition.FacetOrder;
import io.vertigo.datafactory.collections.definitions.FacetRangeDefinitionSupplier;
import io.vertigo.datafactory.collections.definitions.FacetTermDefinitionSupplier;
import io.vertigo.datafactory.collections.definitions.FacetedQueryDefinitionSupplier;
import io.vertigo.datafactory.collections.model.FacetedQueryResult;
import io.vertigo.datafactory.collections.model.SelectedFacetValues;
import io.vertigo.datafactory.search.SearchManager;
import io.vertigo.datafactory.search.definitions.SearchIndexDefinition;
import io.vertigo.datafactory.search.definitions.SearchIndexDefinitionSupplier;
import io.vertigo.datafactory.search.model.SearchQuery;
import io.vertigo.datafactory.search.model.SearchQueryBuilder;
import io.vertigo.datamodel.data.model.DtListState;
import io.vertigo.datamodel.data.model.UID;
import io.mars.basemanagement.domain.BaseIndex;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class BaseIndexSearchClient implements Component, DefinitionProvider {

	private final SearchManager searchManager;
	private final VTransactionManager transactionManager;

	/**
	 * Contructeur.
	 * @param searchManager Search Manager
	 * @param transactionManager Transaction Manager
	 */
	@Inject
	public BaseIndexSearchClient(final SearchManager searchManager, final VTransactionManager transactionManager) {
		this.searchManager = searchManager;
		this.transactionManager = transactionManager;
	}

	/**
	 * Création d'une SearchQuery de type : Base.
	 * @param criteria Critères de recherche
	 * @param selectedFacetValues Liste des facettes sélectionnées à appliquer
	 * @return SearchQueryBuilder pour ce type de recherche
	 */
	public SearchQueryBuilder createSearchQueryBuilderBase(final String criteria, final SelectedFacetValues selectedFacetValues) {
		return SearchQuery.builder("QryBase")
				.withCriteria(criteria)
				.withFacet(selectedFacetValues);
	}

	/**
	 * Récupération du résultat issu d'une requête.
	 * @param searchQuery critères initiaux
	 * @param listState Etat de la liste (tri et pagination)
	 * @return Résultat correspondant à la requête (de type BaseIndex)
	 */
	public FacetedQueryResult<BaseIndex, SearchQuery> loadListIdxBase(final SearchQuery searchQuery, final DtListState listState) {
		final SearchIndexDefinition indexDefinition = io.vertigo.core.node.Node.getNode().getDefinitionSpace().resolve("IdxBase",SearchIndexDefinition.class);
		return searchManager.loadList(indexDefinition, searchQuery, listState);
	}
	/**
	 * Récupération du résultat issu d'une requête.
	 * @param searchQuery critères initiaux
	 * @param listState Etat de la liste (tri et pagination)
	 * @return Résultat correspondant à la requête (de type BaseIndex)
	 */
	public FacetedQueryResult<BaseIndex, SearchQuery> loadListIdxTag(final SearchQuery searchQuery, final DtListState listState) {
		final SearchIndexDefinition indexDefinition = io.vertigo.core.node.Node.getNode().getDefinitionSpace().resolve("IdxTag",SearchIndexDefinition.class);
		return searchManager.loadList(indexDefinition, searchQuery, listState);
	}
		
	/**
	 * Récupération du résultat issu d'une requête.
	 * @param searchQuery critères initiaux
	 * @param listState Etat de la liste (tri et pagination)
	 * @return Résultat correspondant à la requête (de type BaseIndex)
	 */
	public FacetedQueryResult<BaseIndex, SearchQuery> loadList(final SearchQuery searchQuery, final DtListState listState) {
		final List<SearchIndexDefinition> indexDefinitions = List.of( 
				io.vertigo.core.node.Node.getNode().getDefinitionSpace().resolve("IdxBase",SearchIndexDefinition.class),
				io.vertigo.core.node.Node.getNode().getDefinitionSpace().resolve("IdxTag",SearchIndexDefinition.class));
		return searchManager.loadList(indexDefinitions, searchQuery, listState);
	}

	/**
	 * Mark an entity as dirty. Index of these elements will be reindexed if Tx commited.
	 * Reindexation isn't synchrone, strategy is dependant of plugin's parameters.
	 *
	 * @param entityUID Key concept's UID
	 */
	public void markAsDirty(final UID entityUID) {
		transactionManager.getCurrentTransaction().addAfterCompletion((final boolean txCommitted) -> {
			if (txCommitted) {// reindex only is tx successful
				searchManager.markAsDirty(Arrays.asList(entityUID));
			}
		});
	}

	/**
	 * Mark an entity as dirty. Index of these elements will be reindexed if Tx commited.
	 * Reindexation isn't synchrone, strategy is dependant of plugin's parameters.
	 *
	 * @param entity Key concept
	 */
	public void markAsDirty(final io.mars.basemanagement.domain.Base entity) {
		markAsDirty(UID.of(entity));
	}
	/**
	 * Mark an entity as dirty. Index of these elements will be reindexed if Tx commited.
	 * Reindexation isn't synchrone, strategy is dependant of plugin's parameters.
	 *
	 * @param entity Key concept
	 */
	public void markAsDirty(final io.mars.basemanagement.domain.Tag entity) {
		markAsDirty(UID.of(entity));
	}
	
	/**
	 * Simple access to definition, need to call some SearchManager function.
	 * @return SearchDefinition 
	 */
	public SearchIndexDefinition getSearchIndexDefinitionIdxBase() {
		return io.vertigo.core.node.Node.getNode().getDefinitionSpace().resolve("IdxBase",SearchIndexDefinition.class);
	}
	/**
	 * Simple access to definition, need to call some SearchManager function.
	 * @return SearchDefinition 
	 */
	public SearchIndexDefinition getSearchIndexDefinitionIdxTag() {
		return io.vertigo.core.node.Node.getNode().getDefinitionSpace().resolve("IdxTag",SearchIndexDefinition.class);
	}

	/** {@inheritDoc} */
	@Override
	public List<DefinitionSupplier> get(final DefinitionSpace definitionSpace) {
		return new ListBuilder<DefinitionSupplier>()
				//---
				// SearchIndexDefinition
				//-----
				.add(new SearchIndexDefinitionSupplier("IdxBase")
						.withIndexDtDefinition("DtBaseIndex")
						.withKeyConcept("DtBase")
						.withLoaderId("BaseSearchLoader"))
				.add(new SearchIndexDefinitionSupplier("IdxTag")
						.withIndexDtDefinition("DtBaseIndex")
						.withKeyConcept("DtTag")
						.withLoaderId("BaseSearchLoader"))
				
				//---
				// FacetTermDefinition
				//-----
				.add(new FacetTermDefinitionSupplier("FctBaseBaseTypeLabel")
						.withDtDefinition("DtBaseIndex")
						.withFieldName("baseTypeLabel")
						.withLabel("Base Type")
						.withOrder(FacetOrder.count))
				.add(new FacetRangeDefinitionSupplier("FctBaseCreationDate")
						.withDtDefinition("DtBaseIndex")
						.withFieldName("creationDate")
						.withLabel("Creation Date")
						.withRange("r1", "creationDate:[01/01/2008 TO 01/01/2012]", "2008-2012")
						.withRange("r2", "creationDate:[01/01/2012 TO 01/01/2016]", "2012-2016")
						.withRange("r3", "creationDate:[01/01/2016 TO *]", "after 2016")
						.withOrder(FacetOrder.definition))

				//---
				// FacetedQueryDefinition
				//-----
				.add(new FacetedQueryDefinitionSupplier("QryBase")
						.withFacet("FctBaseBaseTypeLabel")
						.withFacet("FctBaseCreationDate")
						.withListFilterBuilderClass(io.vertigo.datafactory.impl.search.dsl.DslListFilterBuilder.class)
						.withListFilterBuilderQuery("baseId:#query# name:#query# code:#+query*#")
						.withCriteriaSmartType("STyLabel"))
				.build();
	}
}
