package io.mars.basemanagement.search;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class GeoSearchEquipmentCriteria implements DtObject {
	private static final long serialVersionUID = 1L;

	private String criteria;
	private io.mars.support.smarttypes.GeoPoint geoUpperLeft;
	private io.mars.support.smarttypes.GeoPoint geoLowerRight;
	private io.mars.support.smarttypes.GeoPoint geoLocation;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Criteria'.
	 * @return String criteria
	 */
	@Field(smartType = "STyLabel", label = "Criteria")
	public String getCriteria() {
		return criteria;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Criteria'.
	 * @param criteria String
	 */
	public void setCriteria(final String criteria) {
		this.criteria = criteria;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'geoUpperLeft'.
	 * @return GeoPoint geoUpperLeft
	 */
	@Field(smartType = "STyGeoPoint", label = "geoUpperLeft")
	public io.mars.support.smarttypes.GeoPoint getGeoUpperLeft() {
		return geoUpperLeft;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'geoUpperLeft'.
	 * @param geoUpperLeft GeoPoint
	 */
	public void setGeoUpperLeft(final io.mars.support.smarttypes.GeoPoint geoUpperLeft) {
		this.geoUpperLeft = geoUpperLeft;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'geoLowerRight'.
	 * @return GeoPoint geoLowerRight
	 */
	@Field(smartType = "STyGeoPoint", label = "geoLowerRight")
	public io.mars.support.smarttypes.GeoPoint getGeoLowerRight() {
		return geoLowerRight;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'geoLowerRight'.
	 * @param geoLowerRight GeoPoint
	 */
	public void setGeoLowerRight(final io.mars.support.smarttypes.GeoPoint geoLowerRight) {
		this.geoLowerRight = geoLowerRight;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'geoLocation'.
	 * @return GeoPoint geoLocation
	 */
	@Field(smartType = "STyGeoPoint", label = "geoLocation")
	public io.mars.support.smarttypes.GeoPoint getGeoLocation() {
		return geoLocation;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'geoLocation'.
	 * @param geoLocation GeoPoint
	 */
	public void setGeoLocation(final io.mars.support.smarttypes.GeoPoint geoLocation) {
		this.geoLocation = geoLocation;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
