resources: 
  - { type: kpr, path: classpath:io/vertigo/easyforms/studio/application.kpr}
  - { type: kpr, path: src/main/resources/io/mars/application.kpr}
  - { type: security, path: src/main/resources/io/mars/basemanagement/base-auth-config.json}
  - { type: security, path: src/main/resources/io/mars/hr/hr-auth-config.json}
mdaConfig:
  projectPackageName: io.mars
  targetGenDir : src/main/
  properties: 
    vertigo.domain.java: true
    vertigo.domain.java.generateDtResources: false
    vertigo.domain.sql: true
    vertigo.domain.sql.targetSubDir: javagen/sqlgen
    vertigo.domain.sql.baseCible: H2
    vertigo.domain.sql.generateDrop: true
    vertigo.domain.sql.generateMasterData: true
    vertigo.task: true
    vertigo.search: true
    vertigo.authorization: true
    mermaid: true