package io.mars.basemanagement.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class BasesSummary implements DataObject {
	private static final long serialVersionUID = 1L;

	private Boolean isLoaded;
	private Long baseCount;
	private Integer baseMeanHealth;
	private Long openedTickets;
	private Integer onlineEquipmentPercent;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Is summary loaded'.
	 * @return Boolean isLoaded <b>Obligatoire</b>
	 */
	@Field(smartType = "STyYesNo", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Is summary loaded")
	public Boolean getIsLoaded() {
		return isLoaded;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Is summary loaded'.
	 * @param isLoaded Boolean <b>Obligatoire</b>
	 */
	public void setIsLoaded(final Boolean isLoaded) {
		this.isLoaded = isLoaded;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Bases count'.
	 * @return Long baseCount <b>Obligatoire</b>
	 */
	@Field(smartType = "STyCount", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Bases count")
	public Long getBaseCount() {
		return baseCount;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Bases count'.
	 * @param baseCount Long <b>Obligatoire</b>
	 */
	public void setBaseCount(final Long baseCount) {
		this.baseCount = baseCount;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Name'.
	 * @return Integer baseMeanHealth <b>Obligatoire</b>
	 */
	@Field(smartType = "STyHealth", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Name")
	public Integer getBaseMeanHealth() {
		return baseMeanHealth;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Name'.
	 * @param baseMeanHealth Integer <b>Obligatoire</b>
	 */
	public void setBaseMeanHealth(final Integer baseMeanHealth) {
		this.baseMeanHealth = baseMeanHealth;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Health Level'.
	 * @return Long openedTickets <b>Obligatoire</b>
	 */
	@Field(smartType = "STyCount", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Health Level")
	public Long getOpenedTickets() {
		return openedTickets;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Health Level'.
	 * @param openedTickets Long <b>Obligatoire</b>
	 */
	public void setOpenedTickets(final Long openedTickets) {
		this.openedTickets = openedTickets;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Equipment Health'.
	 * @return Integer onlineEquipmentPercent <b>Obligatoire</b>
	 */
	@Field(smartType = "STyHealth", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Equipment Health")
	public Integer getOnlineEquipmentPercent() {
		return onlineEquipmentPercent;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Equipment Health'.
	 * @param onlineEquipmentPercent Integer <b>Obligatoire</b>
	 */
	public void setOnlineEquipmentPercent(final Integer onlineEquipmentPercent) {
		this.onlineEquipmentPercent = onlineEquipmentPercent;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
