package io.mars.catalog.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.Entity;
import io.vertigo.datamodel.data.model.UID;
import io.vertigo.datastore.impl.entitystore.StoreVAccessor;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class EquipmentCategory implements Entity {
	private static final long serialVersionUID = 1L;

	private Long equipmentCategoryId;
	private String label;
	private Boolean active;

	@io.vertigo.datamodel.data.stereotype.Association(
			name = "AEquipmentTypeEasyForm",
			fkFieldName = "efoId",
			primaryDtDefinitionName = "DtEasyForm",
			primaryIsNavigable = true,
			primaryRole = "EasyForm",
			primaryLabel = "Equipment Category Meta Form",
			primaryMultiplicity = "0..1",
			foreignDtDefinitionName = "DtEquipmentCategory",
			foreignIsNavigable = false,
			foreignRole = "EquipmentCategory",
			foreignLabel = "EquipmentCategory",
			foreignMultiplicity = "0..*")
	private final StoreVAccessor<io.vertigo.easyforms.domain.EasyForm> efoIdAccessor = new StoreVAccessor<>(io.vertigo.easyforms.domain.EasyForm.class, "EasyForm");

	/** {@inheritDoc} */
	@Override
	public UID<EquipmentCategory> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return Long equipmentCategoryId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Id")
	public Long getEquipmentCategoryId() {
		return equipmentCategoryId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param equipmentCategoryId Long <b>Obligatoire</b>
	 */
	public void setEquipmentCategoryId(final Long equipmentCategoryId) {
		this.equipmentCategoryId = equipmentCategoryId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Equipment Category Label'.
	 * @return String label <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Equipment Category Label")
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Equipment Category Label'.
	 * @param label String <b>Obligatoire</b>
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Equipment category is active'.
	 * @return Boolean active <b>Obligatoire</b>
	 */
	@Field(smartType = "STyYesNo", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Equipment category is active")
	public Boolean getActive() {
		return active;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Equipment category is active'.
	 * @param active Boolean <b>Obligatoire</b>
	 */
	public void setActive(final Boolean active) {
		this.active = active;
	}
	
	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Equipment Category Meta Form'.
	 * @return Long efoId
	 */
	@io.vertigo.datamodel.data.stereotype.ForeignKey(smartType = "STyEfId", label = "Equipment Category Meta Form", fkDefinition = "DtEasyForm" )
	public Long getEfoId() {
		return (Long) efoIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Equipment Category Meta Form'.
	 * @param efoId Long
	 */
	public void setEfoId(final Long efoId) {
		efoIdAccessor.setId(efoId);
	}

 	/**
	 * Association : Equipment Category Meta Form.
	 * @return l'accesseur vers la propriété 'Equipment Category Meta Form'
	 */
	public StoreVAccessor<io.vertigo.easyforms.domain.EasyForm> easyForm() {
		return efoIdAccessor;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
