package io.mars.catalog.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.dynamo.domain.model.KeyConcept;
import io.vertigo.dynamo.domain.model.UID;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
@io.vertigo.dynamo.ngdomain.annotations.Mapper(clazz = io.vertigo.dynamo.domain.util.JsonMapper.class, dataType = io.vertigo.dynamo.domain.metamodel.DataType.String)
public final class Supplier implements KeyConcept {
	private static final long serialVersionUID = 1L;

	private String siren;
	private String statutDiffusion;
	private java.time.LocalDate dateCreation;
	private String sexe;
	private String prenomUsuel;
	private String trancheEffectifs;
	private java.time.Instant dateDernierTraitement;
	private Long nombrePeriodes;
	private String categorieEntreprise;
	private java.time.LocalDate dateDebut;
	private String etatAdministratif;
	private String nom;
	private String nomUsage;
	private String denomination;
	private String categorieJuridique;
	private String activitePrincipale;
	private String nomenclatureActivite;
	private Long nicSiege;
	private Boolean caractereEmployeur;

	/** {@inheritDoc} */
	@Override
	public UID<Supplier> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Siren'.
	 * @return String siren <b>Obligatoire</b>
	 */
	@Field(domain = "STyLabel", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Siren")
	public String getSiren() {
		return siren;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Siren'.
	 * @param siren String <b>Obligatoire</b>
	 */
	public void setSiren(final String siren) {
		this.siren = siren;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Broadcast status'.
	 * @return String statutDiffusion
	 */
	@Field(domain = "STyCode", label = "Broadcast status")
	public String getStatutDiffusion() {
		return statutDiffusion;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Broadcast status'.
	 * @param statutDiffusion String
	 */
	public void setStatutDiffusion(final String statutDiffusion) {
		this.statutDiffusion = statutDiffusion;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Creation date'.
	 * @return LocalDate dateCreation
	 */
	@Field(domain = "STyLocaldate", label = "Creation date")
	public java.time.LocalDate getDateCreation() {
		return dateCreation;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Creation date'.
	 * @param dateCreation LocalDate
	 */
	public void setDateCreation(final java.time.LocalDate dateCreation) {
		this.dateCreation = dateCreation;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Sex'.
	 * @return String sexe
	 */
	@Field(domain = "STyCode", label = "Sex")
	public String getSexe() {
		return sexe;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Sex'.
	 * @param sexe String
	 */
	public void setSexe(final String sexe) {
		this.sexe = sexe;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Firstname'.
	 * @return String prenomUsuel
	 */
	@Field(domain = "STyLabel", label = "Firstname")
	public String getPrenomUsuel() {
		return prenomUsuel;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Firstname'.
	 * @param prenomUsuel String
	 */
	public void setPrenomUsuel(final String prenomUsuel) {
		this.prenomUsuel = prenomUsuel;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Workforce range'.
	 * @return String trancheEffectifs
	 */
	@Field(domain = "STyCode", label = "Workforce range")
	public String getTrancheEffectifs() {
		return trancheEffectifs;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Workforce range'.
	 * @param trancheEffectifs String
	 */
	public void setTrancheEffectifs(final String trancheEffectifs) {
		this.trancheEffectifs = trancheEffectifs;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Last treatment'.
	 * @return Instant dateDernierTraitement
	 */
	@Field(domain = "STyInstant", label = "Last treatment")
	public java.time.Instant getDateDernierTraitement() {
		return dateDernierTraitement;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Last treatment'.
	 * @param dateDernierTraitement Instant
	 */
	public void setDateDernierTraitement(final java.time.Instant dateDernierTraitement) {
		this.dateDernierTraitement = dateDernierTraitement;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Number of periods'.
	 * @return Long nombrePeriodes
	 */
	@Field(domain = "STyCount", label = "Number of periods")
	public Long getNombrePeriodes() {
		return nombrePeriodes;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Number of periods'.
	 * @param nombrePeriodes Long
	 */
	public void setNombrePeriodes(final Long nombrePeriodes) {
		this.nombrePeriodes = nombrePeriodes;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Business category'.
	 * @return String categorieEntreprise
	 */
	@Field(domain = "STyCode", label = "Business category")
	public String getCategorieEntreprise() {
		return categorieEntreprise;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Business category'.
	 * @param categorieEntreprise String
	 */
	public void setCategorieEntreprise(final String categorieEntreprise) {
		this.categorieEntreprise = categorieEntreprise;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Start date'.
	 * @return LocalDate dateDebut
	 */
	@Field(domain = "STyLocaldate", label = "Start date")
	public java.time.LocalDate getDateDebut() {
		return dateDebut;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Start date'.
	 * @param dateDebut LocalDate
	 */
	public void setDateDebut(final java.time.LocalDate dateDebut) {
		this.dateDebut = dateDebut;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Administrative State'.
	 * @return String etatAdministratif
	 */
	@Field(domain = "STyCode", label = "Administrative State")
	public String getEtatAdministratif() {
		return etatAdministratif;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Administrative State'.
	 * @param etatAdministratif String
	 */
	public void setEtatAdministratif(final String etatAdministratif) {
		this.etatAdministratif = etatAdministratif;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Name'.
	 * @return String nom
	 */
	@Field(domain = "STyLabel", label = "Name")
	public String getNom() {
		return nom;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Name'.
	 * @param nom String
	 */
	public void setNom(final String nom) {
		this.nom = nom;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Use name'.
	 * @return String nomUsage
	 */
	@Field(domain = "STyLabel", label = "Use name")
	public String getNomUsage() {
		return nomUsage;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Use name'.
	 * @param nomUsage String
	 */
	public void setNomUsage(final String nomUsage) {
		this.nomUsage = nomUsage;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Denomination'.
	 * @return String denomination
	 */
	@Field(domain = "STyLabel", label = "Denomination")
	public String getDenomination() {
		return denomination;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Denomination'.
	 * @param denomination String
	 */
	public void setDenomination(final String denomination) {
		this.denomination = denomination;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Legal category'.
	 * @return String categorieJuridique
	 */
	@Field(domain = "STyCode", label = "Legal category")
	public String getCategorieJuridique() {
		return categorieJuridique;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Legal category'.
	 * @param categorieJuridique String
	 */
	public void setCategorieJuridique(final String categorieJuridique) {
		this.categorieJuridique = categorieJuridique;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Core business'.
	 * @return String activitePrincipale
	 */
	@Field(domain = "STyCode", label = "Core business")
	public String getActivitePrincipale() {
		return activitePrincipale;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Core business'.
	 * @param activitePrincipale String
	 */
	public void setActivitePrincipale(final String activitePrincipale) {
		this.activitePrincipale = activitePrincipale;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Business nomenclature'.
	 * @return String nomenclatureActivite
	 */
	@Field(domain = "STyCode", label = "Business nomenclature")
	public String getNomenclatureActivite() {
		return nomenclatureActivite;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Business nomenclature'.
	 * @param nomenclatureActivite String
	 */
	public void setNomenclatureActivite(final String nomenclatureActivite) {
		this.nomenclatureActivite = nomenclatureActivite;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Nic Siege'.
	 * @return Long nicSiege
	 */
	@Field(domain = "STyCount", label = "Nic Siege")
	public Long getNicSiege() {
		return nicSiege;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Nic Siege'.
	 * @param nicSiege Long
	 */
	public void setNicSiege(final Long nicSiege) {
		this.nicSiege = nicSiege;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Employer'.
	 * @return Boolean caractereEmployeur
	 */
	@Field(domain = "STyYesNo", label = "Employer")
	public Boolean getCaractereEmployeur() {
		return caractereEmployeur;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Employer'.
	 * @param caractereEmployeur Boolean
	 */
	public void setCaractereEmployeur(final Boolean caractereEmployeur) {
		this.caractereEmployeur = caractereEmployeur;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
