package io.mars.ai.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class AiQuery implements DataObject {
	private static final long serialVersionUID = 1L;

	private java.util.List<io.vertigo.datastore.filestore.model.FileInfoURI> docAllUris = new java.util.ArrayList<>();
	private java.util.List<io.vertigo.datastore.filestore.model.FileInfoURI> docUris = new java.util.ArrayList<>();
	private String prompt;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Files'.
	 * @return List de FileInfoURI docAllUris
	 */
	@Field(smartType = "STyFileInfoURI", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Files")
	public java.util.List<io.vertigo.datastore.filestore.model.FileInfoURI> getDocAllUris() {
		return docAllUris;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Files'.
	 * @param docAllUris List de FileInfoURI
	 */
	public void setDocAllUris(final java.util.List<io.vertigo.datastore.filestore.model.FileInfoURI> docAllUris) {
		io.vertigo.core.lang.Assertion.check().isNotNull(docAllUris);
		//---
		this.docAllUris = docAllUris;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Files'.
	 * @return List de FileInfoURI docUris
	 */
	@Field(smartType = "STyFileInfoURI", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Files")
	public java.util.List<io.vertigo.datastore.filestore.model.FileInfoURI> getDocUris() {
		return docUris;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Files'.
	 * @param docUris List de FileInfoURI
	 */
	public void setDocUris(final java.util.List<io.vertigo.datastore.filestore.model.FileInfoURI> docUris) {
		io.vertigo.core.lang.Assertion.check().isNotNull(docUris);
		//---
		this.docUris = docUris;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Prompt'.
	 * @return String prompt <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Prompt")
	public String getPrompt() {
		return prompt;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Prompt'.
	 * @param prompt String <b>Obligatoire</b>
	 */
	public void setPrompt(final String prompt) {
		this.prompt = prompt;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
