package io.mars.ai.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class AiResponse implements DataObject {
	private static final long serialVersionUID = 1L;

	private io.vertigo.datastore.filestore.model.FileInfoURI docUri;
	private Boolean loading;
	private String fileName;
	private String description;
	private String summary;
	private io.mars.ai.domain.Location location;
	private java.time.LocalDate date;
	private String tags;
	private String persons;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'File'.
	 * @return FileInfoURI docUri <b>Obligatoire</b>
	 */
	@Field(smartType = "STyFileInfoURI", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "File")
	public io.vertigo.datastore.filestore.model.FileInfoURI getDocUri() {
		return docUri;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'File'.
	 * @param docUri FileInfoURI <b>Obligatoire</b>
	 */
	public void setDocUri(final io.vertigo.datastore.filestore.model.FileInfoURI docUri) {
		this.docUri = docUri;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Is loading'.
	 * @return Boolean loading <b>Obligatoire</b>
	 */
	@Field(smartType = "STyYesNo", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Is loading")
	public Boolean getLoading() {
		return loading;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Is loading'.
	 * @param loading Boolean <b>Obligatoire</b>
	 */
	public void setLoading(final Boolean loading) {
		this.loading = loading;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'File'.
	 * @return String fileName <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "File")
	public String getFileName() {
		return fileName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'File'.
	 * @param fileName String <b>Obligatoire</b>
	 */
	public void setFileName(final String fileName) {
		this.fileName = fileName;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Description'.
	 * @return String description <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Description")
	public String getDescription() {
		return description;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Description'.
	 * @param description String <b>Obligatoire</b>
	 */
	public void setDescription(final String description) {
		this.description = description;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Summary'.
	 * @return String summary <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Summary")
	public String getSummary() {
		return summary;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Summary'.
	 * @param summary String <b>Obligatoire</b>
	 */
	public void setSummary(final String summary) {
		this.summary = summary;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Location'.
	 * @return Location location <b>Obligatoire</b>
	 */
	@Field(smartType = "STyDtLocation", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Location")
	public io.mars.ai.domain.Location getLocation() {
		return location;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Location'.
	 * @param location Location <b>Obligatoire</b>
	 */
	public void setLocation(final io.mars.ai.domain.Location location) {
		this.location = location;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Date'.
	 * @return LocalDate date <b>Obligatoire</b>
	 */
	@Field(smartType = "STyLocaldate", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Date")
	public java.time.LocalDate getDate() {
		return date;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Date'.
	 * @param date LocalDate <b>Obligatoire</b>
	 */
	public void setDate(final java.time.LocalDate date) {
		this.date = date;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Tags'.
	 * @return String tags <b>Obligatoire</b>
	 */
	@Field(smartType = "STyMultipleIds", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Tags")
	public String getTags() {
		return tags;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Tags'.
	 * @param tags String <b>Obligatoire</b>
	 */
	public void setTags(final String tags) {
		this.tags = tags;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Persons'.
	 * @return String persons <b>Obligatoire</b>
	 */
	@Field(smartType = "STyMultipleIds", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Persons")
	public String getPersons() {
		return persons;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Persons'.
	 * @param persons String <b>Obligatoire</b>
	 */
	public void setPersons(final String persons) {
		this.persons = persons;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
