package io.mars.ai.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Location implements DataObject {
	private static final long serialVersionUID = 1L;

	private String address;
	private io.mars.support.smarttypes.GeoPoint gps;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Address'.
	 * @return String address <b>Obligatoire</b>
	 */
	@Field(smartType = "STyText", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Address")
	public String getAddress() {
		return address;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Address'.
	 * @param address String <b>Obligatoire</b>
	 */
	public void setAddress(final String address) {
		this.address = address;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Coordinates'.
	 * @return GeoPoint gps <b>Obligatoire</b>
	 */
	@Field(smartType = "STyGeoPoint", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Coordinates")
	public io.mars.support.smarttypes.GeoPoint getGps() {
		return gps;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Coordinates'.
	 * @param gps GeoPoint <b>Obligatoire</b>
	 */
	public void setGps(final io.mars.support.smarttypes.GeoPoint gps) {
		this.gps = gps;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
