package io.mars.catalog.search;

import java.util.Arrays;

import javax.inject.Inject;

import io.vertigo.commons.transaction.VTransactionManager;
import io.vertigo.core.lang.Generated;
import io.vertigo.core.node.Home;
import io.vertigo.core.node.component.Component;
import io.vertigo.core.util.InjectorUtil;
import io.vertigo.datafactory.collections.ListFilter;
import io.vertigo.datafactory.collections.metamodel.FacetedQueryDefinition;
import io.vertigo.datafactory.collections.metamodel.ListFilterBuilder;
import io.vertigo.datafactory.collections.model.FacetedQueryResult;
import io.vertigo.datafactory.collections.model.SelectedFacetValues;
import io.vertigo.datafactory.search.SearchManager;
import io.vertigo.datafactory.search.metamodel.SearchIndexDefinition;
import io.vertigo.datafactory.search.model.SearchQuery;
import io.vertigo.datafactory.search.model.SearchQueryBuilder;
import io.vertigo.dynamo.domain.model.DtListState;
import io.vertigo.dynamo.domain.model.UID;
import io.mars.catalog.domain.Supplier;


/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
@io.vertigo.datafactory.search.metamodel.annotation.SearchIndexAnnotation(name = "IdxSupplier", dtIndex = "DtSupplier", keyConcept = "DtSupplier", loaderId = "SupplierSearchLoader")
public final class SupplierSearchClient implements Component {

	private final SearchManager searchManager;
	private final VTransactionManager transactionManager;

	/**
	 * Contructeur.
	 * @param searchManager Search Manager
	 * @param transactionManager Transaction Manager
	 */
	@Inject
	public SupplierSearchClient(final SearchManager searchManager, final VTransactionManager transactionManager) {
		this.searchManager = searchManager;
		this.transactionManager = transactionManager;
	}

	/**
	 * Création d'une SearchQuery de type : Supplier.
	 * @param criteria Critères de recherche
	 * @param selectedFacetValues Liste des facettes sélectionnées à appliquer
	 * @return SearchQueryBuilder pour ce type de recherche
	 */
	@io.vertigo.datafactory.search.metamodel.annotation.FacetedQueryAnnotation(
		name = "QrySupplier",
		keyConcept = "DtSupplier",
		listFilterBuilderClass = io.vertigo.dynamox.search.DslListFilterBuilder.class,
		listFilterBuilderQuery = "[nom,denomination]:#+query*#",
		criteriaSmartType = "STyLabel",
		facets = {
			@io.vertigo.datafactory.search.metamodel.annotation.Facet(
				type = "term",
				name = "FctSupplierTrancheEffectifs$qrySupplier",
				dtDefinition = "DtSupplier",
				fieldName = "trancheEffectifs",
				label = "Workforce range",
				order = io.vertigo.datafactory.collections.metamodel.FacetDefinition.FacetOrder.count),
			@io.vertigo.datafactory.search.metamodel.annotation.Facet(
				type = "term",
				name = "FctSupplierCategorieEntreprise$qrySupplier",
				dtDefinition = "DtSupplier",
				fieldName = "categorieEntreprise",
				label = "Business category",
				order = io.vertigo.datafactory.collections.metamodel.FacetDefinition.FacetOrder.count),
			@io.vertigo.datafactory.search.metamodel.annotation.Facet(
				type = "term",
				name = "FctSupplierCategorieJuridique$qrySupplier",
				dtDefinition = "DtSupplier",
				fieldName = "categorieJuridique",
				label = "Legal category",
				order = io.vertigo.datafactory.collections.metamodel.FacetDefinition.FacetOrder.count),
			@io.vertigo.datafactory.search.metamodel.annotation.Facet(
				type = "term",
				name = "FctSupplierActivitePrincipale$qrySupplier",
				dtDefinition = "DtSupplier",
				fieldName = "activitePrincipale",
				label = "Core business",
				order = io.vertigo.datafactory.collections.metamodel.FacetDefinition.FacetOrder.count),
			@io.vertigo.datafactory.search.metamodel.annotation.Facet(
				type = "range",
				name = "FctSupplierDateCreation$qrySupplier",
				dtDefinition = "DtSupplier",
				fieldName = "dateCreation",
				label = "Creation date",
				ranges = {
					@io.vertigo.datafactory.search.metamodel.annotation.Range(code = "r1", filter = "dateCreation:[01/01/2000 TO 01/01/2005]", label = "2000-2005"),
					@io.vertigo.datafactory.search.metamodel.annotation.Range(code = "r2", filter = "dateCreation:[01/01/2005 TO 01/01/2010]", label = "2005-2010"),
					@io.vertigo.datafactory.search.metamodel.annotation.Range(code = "r2", filter = "dateCreation:[01/01/2010 TO 01/01/2015]", label = "2010-2015"),
					@io.vertigo.datafactory.search.metamodel.annotation.Range(code = "r3", filter = "dateCreation:[01/01/2015 TO *]", label = "depuis 2015")},
				order = io.vertigo.datafactory.collections.metamodel.FacetDefinition.FacetOrder.definition)		})
	public SearchQueryBuilder createSearchQueryBuilderSupplier(final java.lang.String criteria, final SelectedFacetValues selectedFacetValues) {
		final FacetedQueryDefinition facetedQueryDefinition = Home.getApp().getDefinitionSpace().resolve("QrySupplier", FacetedQueryDefinition.class);
		final ListFilterBuilder<java.lang.String> listFilterBuilder = InjectorUtil.newInstance(facetedQueryDefinition.getListFilterBuilderClass());
		final ListFilter criteriaListFilter = listFilterBuilder.withBuildQuery(facetedQueryDefinition.getListFilterBuilderQuery()).withCriteria(criteria).build();
		return SearchQuery.builder(criteriaListFilter).withFacet(facetedQueryDefinition, selectedFacetValues);
	}

	/**
	 * Récupération du résultat issu d'une requête.
	 * @param searchQuery critères initiaux
	 * @param listState Etat de la liste (tri et pagination)
	 * @return Résultat correspondant à la requête (de type Supplier)
	 */
	public FacetedQueryResult<Supplier, SearchQuery> loadList(final SearchQuery searchQuery, final DtListState listState) {
		final SearchIndexDefinition indexDefinition = searchManager.findFirstIndexDefinitionByKeyConcept(Supplier.class);
		return searchManager.loadList(indexDefinition, searchQuery, listState);
	}

	/**
	 * Mark an entity as dirty. Index of these elements will be reindexed if Tx commited.
	 * Reindexation isn't synchrone, strategy is dependant of plugin's parameters.
	 *
	 * @param entityUID Key concept's UID
	 */
	public void markAsDirty(final UID<Supplier> entityUID) {
		transactionManager.getCurrentTransaction().addAfterCompletion((final boolean txCommitted) -> {
			if (txCommitted) {// reindex only is tx successful
				searchManager.markAsDirty(Arrays.asList(entityUID));
			}
		});
	}

	/**
	 * Mark an entity as dirty. Index of these elements will be reindexed if Tx commited.
	 * Reindexation isn't synchrone, strategy is dependant of plugin's parameters.
	 *
	 * @param entity Key concept
	 */
	public void markAsDirty(final Supplier entity) {
		markAsDirty(UID.of(entity));
	}
}
