package io.mars.maintenance.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DtStaticMasterData;
import io.vertigo.datamodel.data.model.UID;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class TicketStatus implements DtStaticMasterData {
	private static final long serialVersionUID = 1L;

	private String ticketStatusId;
	private String label;

	/** {@inheritDoc} */
	@Override
	public UID<TicketStatus> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return String ticketStatusId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyCode", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Id")
	public String getTicketStatusId() {
		return ticketStatusId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param ticketStatusId String <b>Obligatoire</b>
	 */
	public void setTicketStatusId(final String ticketStatusId) {
		this.ticketStatusId = ticketStatusId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Status Label'.
	 * @return String label
	 */
	@Field(smartType = "STyLabel", label = "Status Label")
	@io.vertigo.datamodel.data.stereotype.SortField
	@io.vertigo.datamodel.data.stereotype.DisplayField
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Status Label'.
	 * @param label String
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
