package io.mars.catalog.dao;

import javax.inject.Inject;

import io.vertigo.core.lang.Generated;
import io.vertigo.core.node.Node;
import io.vertigo.datamodel.task.definitions.TaskDefinition;
import io.vertigo.datamodel.task.model.Task;
import io.vertigo.datamodel.task.model.TaskBuilder;
import io.vertigo.datastore.entitystore.EntityStoreManager;
import io.vertigo.datastore.impl.dao.DAO;
import io.vertigo.datastore.impl.dao.StoreServices;
import io.vertigo.datamodel.smarttype.SmartTypeManager;
import io.vertigo.datamodel.task.TaskManager;
import io.mars.catalog.domain.EquipmentType;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class EquipmentTypeDAO extends DAO<EquipmentType, java.lang.Long> implements StoreServices {

	/**
	 * Contructeur.
	 * @param entityStoreManager Manager de persistance
	 * @param taskManager Manager de Task
	 * @param smartTypeManager SmartTypeManager
	 */
	@Inject
	public EquipmentTypeDAO(final EntityStoreManager entityStoreManager, final TaskManager taskManager, final SmartTypeManager smartTypeManager) {
		super(EquipmentType.class, entityStoreManager, taskManager, smartTypeManager);
	}


	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Node.getNode().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TkSelectEquipmentType.
	 * @return DtList de EquipmentType dtcEquipmentType
	*/
	@io.vertigo.datamodel.task.proxy.TaskAnnotation(
			name = "TkSelectEquipmentType",
			request = """
			select EQUIPMENT_TYPE_ID, LABEL, EQUIPMENT_CATEGORY_ID from EQUIPMENT_TYPE""",
			taskEngineClass = io.vertigo.basics.task.TaskEngineSelect.class)
	@io.vertigo.datamodel.task.proxy.TaskOutput(smartType = "STyDtEquipmentType", name = "dtcEquipmentType")
	public io.vertigo.datamodel.data.model.DtList<io.mars.catalog.domain.EquipmentType> selectEquipmentType() {
		final Task task = createTaskBuilder("TkSelectEquipmentType")
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

}
