package io.mars.hr.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.Data;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class MissionDisplay implements Data {
	private static final long serialVersionUID = 1L;

	private Long missionId;
	private String role;
	private Long baseId;
	private String baseName;
	private String businessName;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return Long missionId
	 */
	@Field(smartType = "STyId", label = "Id")
	public Long getMissionId() {
		return missionId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Id'.
	 * @param missionId Long
	 */
	public void setMissionId(final Long missionId) {
		this.missionId = missionId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Role'.
	 * @return String role
	 */
	@Field(smartType = "STyLabel", label = "Role")
	public String getRole() {
		return role;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Role'.
	 * @param role String
	 */
	public void setRole(final String role) {
		this.role = role;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'BaseId'.
	 * @return Long baseId
	 */
	@Field(smartType = "STyId", label = "BaseId")
	public Long getBaseId() {
		return baseId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'BaseId'.
	 * @param baseId Long
	 */
	public void setBaseId(final Long baseId) {
		this.baseId = baseId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Base'.
	 * @return String baseName
	 */
	@Field(smartType = "STyLabel", label = "Base")
	public String getBaseName() {
		return baseName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Base'.
	 * @param baseName String
	 */
	public void setBaseName(final String baseName) {
		this.baseName = baseName;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Business'.
	 * @return String businessName
	 */
	@Field(smartType = "STyLabel", label = "Business")
	public String getBusinessName() {
		return businessName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Business'.
	 * @param businessName String
	 */
	public void setBusinessName(final String businessName) {
		this.businessName = businessName;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataUtil.toString(this);
	}
}
