package io.mars.hr.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.Data;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class PersonInput implements Data {
	private static final long serialVersionUID = 1L;

	private java.util.List<Long> groups = new java.util.ArrayList<>();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Groups'.
	 * @return List de Long groups
	 */
	@Field(smartType = "STyId", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Groups")
	public java.util.List<Long> getGroups() {
		return groups;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Groups'.
	 * @param groups List de Long
	 */
	public void setGroups(final java.util.List<Long> groups) {
		io.vertigo.core.lang.Assertion.check().isNotNull(groups);
		//---
		this.groups = groups;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataUtil.toString(this);
	}
}
