package io.mars.hr.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DtStaticMasterData;
import io.vertigo.datamodel.data.model.UID;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class Role implements DtStaticMasterData {
	private static final long serialVersionUID = 1L;

	private String roleId;
	private String label;

	/** {@inheritDoc} */
	@Override
	public UID<Role> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return String roleId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyCode", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Id")
	public String getRoleId() {
		return roleId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param roleId String <b>Obligatoire</b>
	 */
	public void setRoleId(final String roleId) {
		this.roleId = roleId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Role Label'.
	 * @return String label
	 */
	@Field(smartType = "STyLabel", label = "Role Label")
	@io.vertigo.datamodel.data.stereotype.SortField
	@io.vertigo.datamodel.data.stereotype.DisplayField
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Role Label'.
	 * @param label String
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataUtil.toString(this);
	}
}
